.\" -*- nroff -*-
.TH FVCBM 1 "10 August 2023" "fvcbm Version 3.1dev"
.SH NAME
fvcbm \- list directories of Commodore 64/128 compatible archive files
.SH SYNOPSIS
.B fvcbm
[
.B \-h
]
[
.B \-d
]
.B filename1
[
.IR filename2 ,
.IR \|.\|.\|.\|filenameN
]
.SH DESCRIPTION
.B fvcbm
displays the directories of Commodore 64 and 128 archive and self-dissolving
archive files, as well as raw floppy disk images.
It can be used to determine what is contained in an archive and how much disk
space it will take when uncompressed.
It is especially useful for previewing files on a network-connected machine
used for downloading Commodore software, and for viewing disk images outside
a Commodore 64 emulator.
.LP
If a given file cannot be found, several standard archive file extensions are
appended to the name in an attempt to find the desired file.
If a file named
.\" Some nroff's don't like: .IR "" ` \- '
`\-'
is given,
.B fvcbm
will attempt to read the standard input for an archive's contents.
Under Linux,
.B fvcbm
can read 1581 disks by specifying the floppy disk device (e.g.
.IR /dev/fd0 ).
The command
.B setfdprm
must first be used to specify that the drive contains a 1581 disk,
which requires a kernel version >= 1.3 (patches to earlier kernels are
available).
.LP
The default (wide) directory display contains a line for each file in the
archive. Each entry's display includes the file name, file type, 
uncompressed length in bytes, uncompressed length in Commodore 254 
byte disk blocks, compression method used, compression savings factor 
(as a percentage reduction of the uncompressed file), and checksum.
.LP
Most columns are totalled in the last line.  Values displayed are the number
of files in the archive, total number of data bytes in the archive, number of
disk blocks required to hold all the files in the archive (not including
archive overhead), the archive type and version number (if known), overall
compression savings factor (not including the extraction program for
self-extracting files), and the number of disk blocks of compressed data
in the archive.
For self-extracting archives, a `+' and
the number of disk blocks taken up by the extraction program are displayed 
following the number of blocks of data.  Adding the numbers
before and after the plus should roughly equal the size of the archive
file on disk (because of padding and rounding, the actual size on disk
may be slightly different).
.LP
The
.B \-d
option selects a style of directory output which is similar to that produced
by Commodore disk drives. Only the file name, size in blocks and
type are displayed for each entry in the archive. The summary line totals
the number of blocks used by the entries.
.LP
.B fvcbm
supports the following archive types: ARC230 (not to be confused with SEA
ARC), self-extracting ARC230 (SDA), Lynx, CS-DOS (LZH), self-extracting
CS-DOS (SFX), LBR (not to be confused with LBR for CP/M), 64Net files
(N64), PC64 emulator files (R/S/U/P00), emulator tape images (T64) and
emulator disk images (D64 and X64), including 1541 and 1581 disk types.
.SH OPTIONS
.TP
.B \-h
Print a help message.
.TP
.B \-d
Display directory in Commodore disk directory format.
.SH "EXIT STATUS"
.B fvcbm
returns the following exit status:
.TP
.B 0
if no errors were encountered
.TP
.B 1
if
.B fvcbm
displayed the help message and exited
.TP
.B 2
if a file could not be found, or a read error occurred
.TP
.B 3
if the file type was not supported
.LP
If more than one filename caused an error, the status will reflect the
last error encountered.
.SH AUTHOR
Daniel Fandrich <dan@coneharvesters.com>
.LP
.B fvcbm
was inspired by Vernon D. Buerg's program 
.I fv
for
displaying directories of MS-DOS archives.
.LP
Thanks to Guntram Blohm, Kevin Brisley, Teemu Rantanen and Haruyasu Yoshizaki
for their reference source code and/or documentation for various archive
formats.  Thanks also to Jouko Valta for beta testing and Tormod Tjaberg for
submitting improvements.
.LP
Feel free to contact the author if you have questions or suggestions for
improvement of the program.

.SH BUGS
Reading an archive from the standard input does not work for some archive
types in some environments; when it does work, the file lengths can be 
incorrect for Lynx and PC64 files. 
Newer versions of some archivers may create files which are not recognized by
.B fvcbm
(please contact the author if you find one).
`Locked' file status for D64 and X64 archive types is not displayed.
.LP
Occasionally, some archive types (especially D64 and ARC) are misidentified.
Convert D64 archives to X64 type archives with
.B c1541
(part of 
.BR x64 )
to read them.
.LP
Older versions of Lynx (at least versions IX
and below) do not explicitly store the length of the final file in the
archive.  This last file can therefore be improperly lengthened if it is
transferred using a file transfer protocol like XMODEM which adds extraneous
characters to the end of transferred files. 
.B fvcbm
(and Lynx itself) has no way of determining if this has happened, and will 
display the incorrect file length if this is the case.  This limitation can
also affect PC64 files.
.SH COPYRIGHT
.B fvcbm
is copyright \(co 1995-2023 by Daniel Fandrich, et. al.
It is provided \(lqas is\(rq, without any express or implied warranties.
See the file COPYING, which should have been included with the program,
for details.
.LP
The words 
.IR Commodore ,
.I Commodore 64 
and 
.I CBM 
are registered trademarks of Escom AG. 
.SH "SEE ALSO"
.BR cbmfs (4),
.BR lha (1),
.BR lscbm (1),
.BR setfdprm (8),
.BR x64 (1)
